### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by pratamov** [sakhnevych/CalendarView#3]
importing the module makes this error

```
Traceback (most recent call last):
  File "generate.py", line 1, in <module>
    from calendar_view.calendar import Calendar
  File "/usr/local/lib/python3.7/dist-packages/calendar_view/calendar.py", line 5, in <module>
    from calendar_view.config import style
  File "/usr/local/lib/python3.7/dist-packages/calendar_view/config/style.py", line 12, in <module>
    title_font = ImageFont.truetype(arial, 50)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 546, in truetype
    return freetype(font)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 543, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 161, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource
```

this is my python version

```
$ python3 --version
Python 3.7.5
```

**Comment by sakhnevych** [comment]
Thanks for reporting. I see the reason. Will fix it soon.

**Comment by sakhnevych** [comment]
The library PIL was not able to find the font `Arial.ttf` on Linux. Fixed by adding the embedded font into the package. I used free font because Arial is a commercial one.

https://github.com/sakhnevych/CalendarView/blob/master/calendar_view/resources/fonts/OldStandard-Regular.ttf

@pratamov, can you check that it works for you?
`pip install -U calendar-view==1.2.0`
